from django.urls import path, include
from django.views.generic import RedirectView

from .views import (
    LoginView,
    LogoutView,
    RegistrosView,
    CargarArchivoPacientesView,
    DescargarBaseDeDatosView,
    AdministracionUsuariosView,
    VariablasClinicasView,
    SegmentacionGruposView,
    SeguimientoPacientesView,
    DatosPacienteView,
    PerfilamientoPacienteView,
    TareasPacienteView,
    IndicadoresPacienteView,
    MetasPacienteView,
    SeguimientoGruposView,
    GrupoPacientesView,
    IndicadoresHtaView,
    IndicadoresDmView,
    IndicadoresErcView,
    OtrosIndicadoresView,
    DetalleIndicadorView,
    GruposEtareosView,
    IndicadoresView,
    TareasView,
    GruposPacientesView,
    MedicacionView,
    AdministracionUsuariosApiView,
    SeguimientoPacientesApiView,
    UpdateAdminView,
    ControlesPacienteView,
    ExamenesPacienteView,
    HospitalizacionesPacienteView,
    TendenciasPacienteView,
    CargaRegistrosView,
    DetallesVariable,
    CalcIndicadorView,
    DownloadExcelView,
)


urlpatterns = [
    path("ingresar", LoginView.as_view(), name="login"),
    path("cerrar-sesion", LogoutView.as_view(), name="logout"),
    path('descargar-excel/', DownloadExcelView.as_view(), name='descargar_excel'),
    path(
        "registros/",
        include(
            [
                path("", RegistrosView.as_view(), name="registros-index"),
                path(
                    "cargar-archivo-pacientes",
                    CargarArchivoPacientesView.as_view(),
                    name="cargar-archivo-pacientes",
                ),
                path(
                    "descargar-base-datos",
                    DescargarBaseDeDatosView.as_view(),
                    name="descargar-base-datos",
                ),
                path(
                    "cargar-registros/<str:model>",
                    CargaRegistrosView.as_view(),
                    name="cargar-registros",
                ),
                path("<str:slug>", RegistrosView.as_view(), name="registros"),
            ]
        ),
    ),
    path(
        "segmentacion/",
        include(
            [
                path(
                    "",
                    RedirectView.as_view(pattern_name="gi:variables-clinicas"),
                    name="segmentacion",
                ),
                path(
                    "dashboard/",
                    include(
                        [
                            path(
                                "",
                                VariablasClinicasView.as_view(),
                                name="variables-clinicas",
                            ),
                            path(
                                "<str:slug>",
                                DetallesVariable.as_view(),
                                name="detalle-variable",
                            ),
                        ]
                    ),
                ),
                path(
                    "grupos/",
                    include(
                        [
                            path(
                                "",
                                SegmentacionGruposView.as_view(),
                                name="segmentacion-grupos",
                            ),
                            path(
                                "<str:slug_grupo>/",
                                include(
                                    [
                                        path(
                                            "",
                                            VariablasClinicasView.as_view(),
                                            name="dashboard-segmentacion-grupo",
                                        ),
                                        path(
                                            "<str:slug>",
                                            VariablasClinicasView.as_view(),
                                            name="detalle-segmentacion-grupo",
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
            ]
        ),
    ),
    path(
        "seguimiento/",
        include(
            [
                path(
                    "",
                    RedirectView.as_view(pattern_name="gi:seguimiento-pacientes"),
                    name="seguimiento",
                ),
                path(
                    "pacientes/",
                    include(
                        [
                            path(
                                "",
                                SeguimientoPacientesView.as_view(),
                                name="seguimiento-pacientes",
                            ),
                            path(
                                "api",
                                SeguimientoPacientesApiView.as_view(),
                                name="api-seguimiento-pacientes",
                            ),
                            path(
                                "crear",
                                DatosPacienteView.as_view(),
                                name="crear-datos-paciente",
                            ),
                            path(
                                "<int:id_paciente>/",
                                include(
                                    [
                                        path(
                                            "",
                                            DatosPacienteView.as_view(),
                                            name="datos-paciente",
                                        ),
                                        path(
                                            "perfilamiento",
                                            PerfilamientoPacienteView.as_view(),
                                            name="perfilamiento-paciente",
                                        ),
                                        path(
                                            "tareas",
                                            TareasPacienteView.as_view(),
                                            name="tareas-paciente",
                                        ),
                                        path(
                                            "controles",
                                            ControlesPacienteView.as_view(),
                                            name="controles-paciente",
                                        ),
                                        path(
                                            "hospitalizaciones",
                                            HospitalizacionesPacienteView.as_view(),
                                            name="hospitalizaciones-paciente",
                                        ),
                                        path(
                                            "examenes",
                                            ExamenesPacienteView.as_view(),
                                            name="examenes-paciente",
                                        ),
                                        path(
                                            "metas/",
                                            include(
                                                [
                                                    path(
                                                        "",
                                                        TendenciasPacienteView.as_view(),
                                                        name="tendencias-paciente",
                                                    ),
                                                    path(
                                                        "metas",
                                                        MetasPacienteView.as_view(),
                                                        name="metas-paciente",
                                                    ),
                                                    path(
                                                        "indicadores",
                                                        IndicadoresPacienteView.as_view(),
                                                        name="indicadores-paciente",
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
                path(
                    "grupos/",
                    include(
                        [
                            path(
                                "",
                                SeguimientoGruposView.as_view(),
                                name="seguimiento-grupos",
                            ),
                            path(
                                "<str:slug_grupo>",
                                GrupoPacientesView.as_view(),
                                name="grupo-pacientes",
                            ),
                        ]
                    ),
                ),
            ]
        ),
    ),
    path(
        "indicadores/",
        include(
            [
                path(
                    "",
                    RedirectView.as_view(pattern_name="gi:indicadores-dm"),
                    name="indicadores-poblacional",
                ),
                path("hta", IndicadoresHtaView.as_view(), name="indicadores-hta"),
                path("dm", IndicadoresDmView.as_view(), name="indicadores-dm"),
                path("erc", IndicadoresErcView.as_view(), name="indicadores-erc"),
                path("otros", OtrosIndicadoresView.as_view(), name="indicadores-otros"),
                path(
                    "<str:tipo_indicador>/<str:id_indicador>",
                    DetalleIndicadorView.as_view(),
                    name="detalle-indicador",
                ),
                path(
                    "<str:tipo_indicador>/<str:id_indicador>/calc",
                    CalcIndicadorView.as_view(),
                    name="calc-indicador",
                ),
            ]
        ),
    ),
    path(
        "parametros/",
        include(
            [
                path(
                    "",
                    RedirectView.as_view(pattern_name="gi:grupos-etareos"),
                    name="parametros",
                ),
                path(
                    "grupos-etareos", GruposEtareosView.as_view(), name="grupos-etareos"
                ),
                path("indicadores", IndicadoresView.as_view(), name="indicadores"),
                path("tareas", TareasView.as_view(), name="tareas"),
                path(
                    "grupos-pacientes",
                    GruposPacientesView.as_view(),
                    name="grupos-pacientes",
                ),
                path("medicacion", MedicacionView.as_view(), name="medicacion"),
            ]
        ),
    ),
    path(
        "usuarios/",
        include(
            [
                path(
                    "",
                    RedirectView.as_view(pattern_name="gi:administracion-usuarios"),
                    name="usuarios",
                ),
                path(
                    "administracion",
                    AdministracionUsuariosView.as_view(),
                    name="administracion-usuarios",
                ),
                path(
                    "api-admin",
                    AdministracionUsuariosApiView.as_view(),
                    name="api-admin-usuarios",
                ),
                path(
                    "admin-update", UpdateAdminView.as_view(), name="admin-update-user"
                ),
            ]
        ),
    ),
    path("", RedirectView.as_view(pattern_name="gi:registros-index"), name="index"),
]
