CONFIGURACIONES_CARGUE = {
    "Examenes": {
        "sheet_name": 0,
        "header": 0,
        "all_columns": [
            "paciente",
            "tsh",
            "alat",
            "glicemia_basal",
            "asat",
            "microalbuminuria",
            "creatinina",
            "hdl",
            "ldl",
            "ct",
            "hemoglobina_glicosilada",
            "fecha",
        ],
        "unique_columns": [],
        "mandatory_columns": [],
        "dtypes_dict": {
            "paciente": int,
            "tsh": float,
            "alat": float,
            "glicemia_basal": float,
            "asat": float,
            "microalbuminuria": float,
            "creatinina": float,
            "hdl": float,
            "ldl": float,
            "ct": float,
            "hemoglobina_glicosilada": float,
            "fecha": str,
        },
        "rename_dict": {},
        "map_dicts": {},
        "date_formats_dict": {"fecha": "%Y-%m-%d"},
    },
    "Hospitalizaciones": {
        "sheet_name": 0,
        "header": 0,
        "all_columns": [
            "paciente",
            "diagnostico_cie",
            "tipo",
            "era_evitable",
            "relacionado_con_diabetes",
            "observaciones",
            "tiene_soporte",
            "fecha",
        ],
        "unique_columns": [],
        "mandatory_columns": [],
        "dtypes_dict": {
            "paciente": str,
            "diagnostico_cie": float,
            "tipo": float,
            "era_evitable": str,
            "relacionado_con_diabetes": str,
            "observaciones": str,
            "tiene_soporte": str,
            "fecha": str,
        },
        "rename_dict": {},
        "map_dicts": {},
        "date_formats_dict": {"fecha": "%Y-%m-%d"},
    },
    "Controles": {
        "sheet_name": 0,
        "header": 0,
        "all_columns": [
            "paciente",
            "tipo",
            "tas",
            "tad",
            "peso",
            "glucometria",
            "numero_eventos_hipoglicemia",
            "observaciones",
            "tiene_soporte",
            "fecha",
        ],
        "unique_columns": [],
        "mandatory_columns": [],
        "dtypes_dict": {
            "paciente": str,
            "tipo": str,
            "tas": float,
            "tad": float,
            "peso": float,
            "glucometria": float,
            "numero_eventos_hipoglicemia": float,
            "observaciones": str,
            "tiene_soporte": str,
            "fecha": str,
        },
        "rename_dict": {},
        "map_dicts": {},
        "date_formats_dict": {"fecha": "%Y-%m-%d"},
    },
    "VariablesClinicas": {
        "sheet_name": 0,
        "header": 0,
        "all_columns": [
            "nombres",
            "apellidos",
            "tipo_documento",
            "numero_documento",
            "fecha_nacimiento",
            "genero",
            "tas",
            "colesterol_total",
            "riesgo_cardiovascular",
            "nivel_riesgo_rcv",
            "grupo_etnico",
            "estado_civil",
            "nivel_estudios",
            "estrato",
            "direccion",
            "barrio",
            "telefono",
            "telefono_emergencia",
            "fecha_afiliacion",
            "tipo_diabetes",
            "fecha_diagnostico",
            "diagnostico",
            "diagnostico_hta",
            "diagnostico_erc",
            "diagnostico_epoc",
            "diagnostico_hipoglicemia",
            "diagnostico_falla_cardiaca",
            "tad",
            "es_fumador",
            "estatura",
            "peso",
            "programa_nefroproteccion",
            "tfg",
            "ultimo_seguimiento",
            "eps",
            "grupo_gestion",
            "ciudad_asignacion",
            "ciudad_contacto",
            "estadio",
            "tsh",
            "alat",
            "glicemia_basal",
            "asat",
            "microalbuminuria",
            "creatinina",
            "hdl",
            "ldl",
            "ct",
            "hemoglobina_glicosilada",
            "tipo",
            "glucometria",
            "numero_eventos_hipoglicemia",
            "observaciones",
            "fecha_erc",
            "fecha_hta",
            "numero_hospitalizaciones",
            "hba1c",
            "fecha_dm",
        ],
        "unique_columns": [],
        "mandatory_columns": [],
        "dtypes_dict": {
            "nombres": str,
            "apellidos": str,
            "tipo_documento": str,
            "numero_documento": str,
            "fecha_nacimiento": str,
            "genero": str,
            "tas": float,
            "colesterol_total": float,
            "riesgo_cardiovascular": float,
            "nivel_riesgo_rcv": str,
            "grupo_etnico": str,
            "estado_civil": str,
            "nivel_estudios": str,
            "estrato": str,
            "direccion": str,
            "barrio": str,
            "telefono": str,
            "telefono_emergencia": str,
            "fecha_afiliacion": str,
            "tipo_diabetes": str,
            "fecha_diagnostico": str,
            "diagnostico": str,
            "diagnostico_hta": str,
            "diagnostico_erc": str,
            "diagnostico_epoc": str,
            "diagnostico_hipoglicemia": str,
            "diagnostico_falla_cardiaca": str,
            "tad": float,
            "es_fumador": str,
            "estatura": float,
            "peso": float,
            "programa_nefroproteccion": str,
            "tfg": float,
            "ultimo_seguimiento": str,
            "eps": str,
            "grupo_gestion": str,
            "ciudad_asignacion": str,
            "ciudad_contacto": str,
            "estadio": str,
            "tsh": float,
            "alat": float,
            "glicemia_basal": float,
            "asat": float,
            "microalbuminuria": float,
            "creatinina": float,
            "hdl": float,
            "ldl": float,
            "ct": float,
            "hemoglobina_glicosilada": float,
            "tipo": str,
            "glucometria": str,
            "numero_eventos_hipoglicemia": float,
            "observaciones": str,
            "fecha_erc": str,
            "fecha_hta": str,
            "numero_hospitalizaciones": float,
            "hba1c": float,
            "fecha_dm": str,
        },
        "rename_dict": {},
        "map_dicts": {},
        "date_formats_dict": {
            "fecha_nacimiento": "%Y-%m-%d",
            "fecha_afiliacion": "%Y-%m-%d",
            "fecha_diagnostico": "%Y-%m-%d",
            "fecha_erc": "%Y-%m-%d",
            "fecha_hta": "%Y-%m-%d",
            "fecha_dm": "%Y-%m-%d",
        },
    },
}

TIME_ZONE = "America/Bogota"
