from ._01_demografico import Demografico
from ._02_hba1c import Hemoglobina
from ._03_imc import Imc
from ._04_cardiovascular import CardioVascular
from ._05_erc import Erc
from ._06_hipoglicemia import Hipoglicemia
from ._07_tratamientos import Tratamientos
from ._08_estadios import Estadios
from ._09_genero import Genero
from ._10_estado_civil import EstadoCivil
from ._11_general import General
from ._12_escolaridad import Escolaridad
