# Generated by Django 3.1.6 on 2024-06-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nivel_riesgo_rcv',
            field=models.CharField(choices=[('Sin información', 'Sin información'), ('Bajo', 'Bajo'), ('Moderado', 'Moderado'), ('Alto', 'Alto'), ('Muy alto', 'Muy alto')], default='', editable=False, max_length=100, verbose_name='Nivel de riesgo RCV'),
        ),
    ]
